### ISSUE TITLE
Axis labeling in R paper & on github

### ISSUE THREAD

**Issue by SimonDedman** [jfrench/autoimage#1]
Hi Josh,

Cool package, looks really nice & simple, definitely will be looking into using it.

One quick thing: I noticed Figures 7:9 have "lon" as both axis labels in the paper & on the github package front page; other figures have e.g. co$lon which you may or may not want to change. Since it's pdf constructed from latex (IIRC? Haven't submitted to the journal yet but looked into it) I imagine it might be possible to change & recompile, else manually edit in e.g. pdfmaster & email to the journal & ask them to overwrite the file in place?

Cheers. Since I'm typing: am I correct in thinking that a table of lat/lon/Zvalue points will have grid spacing set automatically?

Simon

**Comment by jpfrench81** [comment]
Hi Simon,

Thanks for your suggestion.  The R journal article is finalized, so no more changes can be made.  I could update the vignette though.

My thinking on this was that since I wanted to demonstrate the functionality of the package, I would have graphics both with and without customization.  Not all of them would look as nice as possible, but it would make it easier to see what the different options do.  Based on the graphics you mentioned, the user (hopefully) realizes that the axis labels are pulled directly from the name of the x and y objects provided to autoimage.  Does this make sense?  If not, perhaps I will change the vignette.

Regarding your second question, yes, the spacing of the grid is automatically determined based on the x and y values provided.  It is essentially assumed that the points provided represent the midpoint of the pixels.
